---
ID: "a4616ec3-c3da-4775-ba7d-a7b3216b0a71"
Parent: "b73a9f21-c606-4e51-91f1-4f7db5f01f82"
Template: "b73a9f21-c606-4e51-91f1-4f7db5f01f82"
Path: /sitecore/templates/Project/BasicCompany/Page Types/News/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{4ED48317-062F-4465-B9AF-1E636841525B}">
        <r
          id="{AF0D28F1-B659-4392-8FCF-E250DF527FA3}"
          ph="header"
          uid="{5B4893F1-86BA-4ABA-8CB3-1BD6B0D10CB0}" />
        <r
          id="{78BCD6B7-FB7B-4D9D-90D1-78A2C45FCF49}"
          ph="footer"
          uid="{D40CD9A3-CC19-4772-AA17-191F399340C9}" />
        <r
          id="{8C3526E5-295C-47B8-B7E2-2264A1BE9C0A}"
          ph="main"
          uid="{395B20FC-B456-4691-B1D8-0C7255380C0F}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211105T103821Z
